# MySQL Connection Properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sunbasedata
    username: root
    password: root@786
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
